admin/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("login", views.signin, name="admin_login"),
    path("logout", views.sign_out, name="admin_logout"),
    path("register", views.admin_create, name="admin_create"),

    path("payments/<str:user_email>", views.view_payments, name="admin_payments"),
    path("requests/<str:user_email>", views.view_requests, name="admin_requests"),
]

payapp/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path("pay", views.view_make_payment, name="pay"),
    path("request", views.view_make_request, name="request"),

    path("approve", views.approve_request, name="approve"),
    path("deny", views.deny_request, name="deny"),

    path("payments", views.view_payments, name="payments"),
    path("requests", views.view_requests, name="requests"),

    path("notifications", views.view_notifications, name="notifications"),

    path("mark_read", views.mark_read, name="mark_read"),
    path("mark_unread", views.mark_unread, name="mark_unread"),
    path("delete_notification", views.delete_notifications, name="delete_notification"),
]

webapps2025/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.shortcuts import HttpResponse
from django.http.response import HttpResponse

from accounts.views import home

urlpatterns = [
    path("webapps2025/admin/", include("admin.urls")),

    path("webapps2025/", include("accounts.urls")),

    path("webapps2025/register/", include("register.urls")),
    path('webapps2025/conversion/', include('conversion.urls')),
    path('webapps2025/', include('payapp.urls')),


]

payapp/forms.py
from django import forms

from accounts.models import Account

from utils.currency import CurrencyAmount

from typing import Tuple


class TransferForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"autofocus": True}), max_length=254)
    amount = forms.DecimalField(label="Amount")

    def __init__(self, *args, user: Account|None=None, **kwargs):
        super().__init__(*args, **kwargs)

        if user is None:
            raise forms.ValidationError("Must provide the user")

        self.user: Account = user 

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email == self.user.email:
            raise forms.ValidationError("You cannot use your own email")

        try:
            self.checked_user = Account.objects.get(email=email)
        except Account.DoesNotExist: 
            raise forms.ValidationError("Account doesn't exist")

        return email


    def clean_amount(self):
        amount = self.cleaned_data.get("amount") 

        if amount is None:
            raise forms.ValidationError("Amount not provided")

        if amount < 1:
            raise forms.ValidationError("Minimum amount is 1.00 " + self.user.currency)

        amount_str = str(amount).split(".")

        if len(amount_str) == 2 and len(amount_str[1]) > 2:
            raise forms.ValidationError("Amount should be in the format 100.00. Only two decimal places are allowed.")


        self.amount: CurrencyAmount = CurrencyAmount(amount)
        return amount


    def get_payment_data(self) -> Tuple[Account, Account, CurrencyAmount]:
        sender: Account = self.user
        receiver = self.checked_user
        amount = self.amount

        return sender, receiver, amount


    def get_request_data(self) -> Tuple[Account, Account, CurrencyAmount]:
        receiver = self.user
        sender = self.checked_user
        amount = self.amount

        return sender, receiver, amount

payapp/views.py
from decimal import Decimal
from enum import Enum

from django.http.response import HttpResponseForbidden, HttpResponseServerError
from services.currency import CurrencyAmount, call_conversion_api
from django.db import IntegrityError, transaction


from django.contrib.auth.decorators import login_required


from django.shortcuts import render, redirect


from django.db.models import Q


from django.contrib import messages


from typing import Union, Type

from accounts.models import Account
from .models import Payment
from .models import Request
from .models import Notification



from .forms import TransferForm


from accounts.views import login_required

class TransferResult(Enum):
    Ok = "success"
    InsufficientFunds = "Failed to make payment due to insufficient funds"
    CurrencyExchangFaillure = "Server error due to currency conversion"
    InvalidStringValueForAmount = "Invalid string value for currency amount"
    TransactionFailure = "Server error due to transaction failure"


def non_atomic_make_payment(request, sender: Account, receiver: Account, amount_input: CurrencyAmount) -> TransferResult:
    rate = CurrencyAmount(1)

    source: str = sender.currency
    target: str = receiver.currency


    amount = amount_input.into()

    if amount > sender.balance:
        return TransferResult.InsufficientFunds

    if (source != target):
        amount_str = CurrencyAmount(amount).to_api_str()

        try:
            result_json = call_conversion_api(request, source, target, amount_str)
            rate = CurrencyAmount(result_json["rate"])
        except Exception as e:
            print(e)
            return TransferResult.CurrencyExchangFaillure


    amount = CurrencyAmount(amount)
    
    sender_amount = amount
    receiver_amount = CurrencyAmount((amount * rate).into())


    sender_balance = (CurrencyAmount(sender.balance) - sender_amount).into()
    receiver_balance = (CurrencyAmount(receiver.balance) + receiver_amount).into()



    sender.balance = sender_balance
    receiver.balance = receiver_balance


    sender.save()
    receiver.save()



    sender_amount = sender_amount.into()
    receiver_amount = receiver_amount.into()


    payment: Payment = Payment(
            sender=sender, receiver=receiver, 
            sender_amount=sender_amount, receiver_amount=receiver_amount, rate=rate.into()) 


    payment.save()


    return TransferResult.Ok


def non_atomic_make_request(request, sender: Account, receiver: Account, amount_input: CurrencyAmount) -> TransferResult:
    rate = CurrencyAmount(1)

    source: str = receiver.currency
    target: str = sender.currency

    amount = amount_input.into()

    if (source != target):
        amount_str = CurrencyAmount(amount).to_api_str()

        try:
            result_json = call_conversion_api(request, source, target, amount_str)
            rate = CurrencyAmount(result_json["rate"])
        except Exception as e:
            print(e)
            return TransferResult.CurrencyExchangFaillure


    amount = CurrencyAmount(amount)
    
    receiver_amount = amount.into()
    sender_amount = (amount * rate).into()

    payment_request: Request = Request(
            sender=sender, receiver=receiver, 
            sender_amount=sender_amount, receiver_amount=receiver_amount, rate=rate.into()) 

    payment_request.save()

    return TransferResult.Ok


def make_payment(request, sender: Account, receiver: Account, amount_input: CurrencyAmount) -> TransferResult:
    try:
        with transaction.atomic():
            return non_atomic_make_payment(request, sender, receiver, amount_input)
    except Exception as e:
        print(e)
        return TransferResult.TransactionFailure


def make_request(request, sender: Account, receiver: Account, amount_input: CurrencyAmount) -> TransferResult:
    try:
        with transaction.atomic():
            return non_atomic_make_request(request, sender, receiver, amount_input)
    except Exception as e:
        print(e)
        return TransferResult.TransactionFailure


@login_required
def view_make_payment(request):
    transfer_type = "payment"
    if request.method == "GET":
        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type})

    if request.method != "POST":
        return HttpResponseForbidden()

    form = TransferForm(request.POST, user=request.user)
    form_invalid = not form.is_valid()
    if form_invalid:
        exception = (list(form.errors.as_data().values())[0][0]).messages[0]
        messages.error(request, exception)

        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type, "form": form})
    

    sender, receiver, amount = form.get_payment_data()


    result = make_payment(request, sender, receiver, amount)


    if result != TransferResult.Ok:
        messages.error(request, result.value)
        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type, "form": form})


    return redirect("home")


@login_required
def view_make_request(request):
    transfer_type = "request"
    if request.method == "GET":
        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type})

    if request.method != "POST":
        return HttpResponseForbidden()

    form = TransferForm(request.POST, user=request.user)
    form_invalid = not form.is_valid()
    if form_invalid:
        exception = (list(form.errors.as_data().values())[0][0]).messages[0]
        messages.error(request, exception)

        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type, "form": form})
    

    sender, receiver, amount = form.get_request_data()

    result = make_request(request, sender, receiver, amount)


    if result != TransferResult.Ok:
        messages.error(request, result.value)
        return render(request, "payapp/make_transfer.html", {"transfer_type": transfer_type, "form": form})


    return redirect("home")



@login_required
def view_payments(request):
    account = request.user

    payments = Payment.objects.filter( Q(sender=account) | Q(receiver=account) ).order_by("-date")

    for payment in payments:
        payment.incoming = payment.receiver == account
        payment.sender_amount = CurrencyAmount(payment.sender_amount).to_api_str()
        payment.receiver_amount = CurrencyAmount(payment.receiver_amount).to_api_str()

    return render(request, "payapp/payments.html", {'payments': payments} )

@login_required
def view_requests(request):
    http_request = request
    account = request.user


    requests = Request.objects.filter( Q(sender=account) | Q(receiver=account) ).order_by("-date")


    for request in requests:
        request.incoming = request.receiver == account

        status = request.status

        if status == "P":
            status = "Pending"
        elif status == "A":
            status = "Approved"
        elif status == "D":
            status = "Denied"
        else:
           return HttpResponseServerError() 

        request.status = status
        request.sender_amount = CurrencyAmount(request.sender_amount).to_api_str()
        request.receiver_amount = CurrencyAmount(request.receiver_amount).to_api_str()



    return render(http_request, "payapp/requests.html", { "requests": requests, "user": account })




def non_atomic_apply_request(request: Request) -> TransferResult:
    sender = request.sender
    receiver = request.receiver


    sender_amount = CurrencyAmount(request.sender_amount)
    receiver_amount = CurrencyAmount(request.receiver_amount)
    rate = request.rate

    
    sender_balance = (CurrencyAmount(sender.balance) - sender_amount).into()
    receiver_balance = (CurrencyAmount(receiver.balance) + receiver_amount).into()


    sender.balance = sender_balance
    receiver.balance = receiver_balance

    sender.save()
    receiver.save()


    payment: Payment = Payment(
        sender=sender, 
        receiver=receiver, 
        sender_amount=sender_amount, 
        receiver_amount=receiver_amount, 
        rate=rate, 
        from_request=True
    ) 

    payment.save()

    request.status = "A"
    request.save()

    return TransferResult.Ok


def apply_request(request: Request) -> TransferResult:
    if request.sender_amount > request.sender.balance:
        return TransferResult.InsufficientFunds

    try:
        with transaction.atomic():
            return non_atomic_apply_request(request)

    except Exception as e:
        print(e)
        return TransferResult.TransactionFailure





@login_required
def approve_request(request):
    if request.method != "POST":
        return HttpResponseForbidden()

    user = request.user
    request_id = request.POST.get("request_id")

    approved_request: Request | None = Request.objects.filter(id=request_id).first()


    if approved_request is None:
        messages.error(request, "Accepted request does not exist")
        return redirect("requests")

    if approved_request.status != "P":
        messages.error(request, "Request can only be accepted if pending")
        return redirect("requests")


    if approved_request.sender != user:
        messages.error(request, "Sender mismatch")
        return redirect("requests")


    result: TransferResult = apply_request(approved_request)


    if result == TransferResult.InsufficientFunds:
        messages.error(request, "Failed due to insufficient funds.")
        return redirect("requests")


    if result == TransferResult.TransactionFailure:
        messages.error(request, "Failed due to server error. Try again later.")
        return redirect("requests")

    if approved_request.sender != request.user:
        messages.error(request, "Sender mismatch")
        return redirect("requests")

    return redirect("requests")



@login_required
def deny_request(request):
    if request.method != "POST":
        return HttpResponseForbidden()

    user = request.user

templates/payapp/make_transfer.html
{% extends "signed_in.html" %}
{% block content %}

<div style="display: flex; height: calc(100vh - {{ nav_height }}); background-color: black;">
  <div class="d-flex justify-content-center align-items-center flex-column flex-grow-1 ">
    <div class="rounded shadow p-5 w-50 h-50" style="background-color: white; margin-bottom: 20vh;">

      <h2>Make {% if transfer_type == "payment" %}Payment{% else %}Request{% endif %}</h2>
      <form method="POST">
          {% csrf_token %}

          {% if messages %}
          <div class="mb-3">
              {% for message in messages %}
                  <div class="alert alert-{% if 'error' in message.tags %}danger{% else %}{{ message.tags }}{% endif %} mb-2"
                       role="alert">
                      {{ message }}
                  </div>
              {% endfor %}
          </div>
          {% endif %}


          <label for="email" >{% if transfer_type == "payment" %}Receiver{% else %}Sender{% endif %}'s Email</label>
          <input type="email" name="email" id="id_email" class="form-control" required value="{{ form.email.value|default:'' }}">

          <label for="amount" >Amount</label>
          <input type="number" name="amount" id="id_amount" class="form-control mb-2" required step="0.01" value="{{ form.amount.value|default:'' }}">


          <button type="submit">Confirm</button>
      </form>


      
    </div>
  </div>
</div>

{% endblock %}

templates/payapp/notifications.html
{% extends "signed_in.html" %}
{% block content %}

<div style="display: flex; height: calc(100vh - {{ nav_height }}); background-color: black;">
  <div class="d-flex justify-content-center align-items-center flex-column flex-grow-1 ">
    <div class="rounded shadow p-5 w-50" style="background-color: white; height: calc( calc(100vh - {{ nav_height }}) * 0.8 ); display: flex; flex-direction: column;">
      <h2>Notifications</h2>



      <div class="container mt-4" style="overflow-y: auto;">

  {% if notifications %}
    <div class="list-group" style="overflow-y: auto;">


      {% for notification in notifications %}

        <div class="list-group-item d-flex justify-content-between align-items-center" style="overflow-y: auto;">

          <div>

            {{ notification.message }}

          </div>

          {% if notification.status == "U" %}

              <form action="{% url 'mark_read' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="notification_id" value="{{ notification.id }}">
                <button class="btn btn-primary" style="cursor: pointer;" onclick="this.onsest('form').submit();">
                  Mark Read
                </button>
              </form>

          {% else %}

              <form action="{% url 'mark_unread' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="notification_id" value="{{ notification.id }}">
                <button class="btn btn-primary" style="cursor: pointer;" onclick="this.onsest('form').submit();">
                  Mark Unread
                </button>
              </form>

          {% endif %}

              <form action="{% url 'delete_notification' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="notification_id" value="{{ notification.id }}">
                <button class="btn btn-danger" style="cursor: pointer;" onclick="this.onsest('form').submit();">
                  Delete
                </button>
              </form>

        </div>

      {% endfor %}



    </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      No notifications found.
    </div>
  {% endif %}







    </div>
  </div>
</div>
{% endblock %}

templates/payapp/payments.html
{% extends "signed_in.html" %}
{% block content %}

<div style="display: flex; height: calc(100vh - {{ nav_height }}); background-color: black;">
  <div class="d-flex justify-content-center align-items-center flex-column flex-grow-1 ">
    <div class="rounded shadow p-5 w-50" style="background-color: white; height: calc( calc(100vh - {{ nav_height }}) * 0.8 ); display: flex; flex-direction: column;">


  <div class="d-flex align-items-center justify-content-between">
      <h2>Payments</h2>

    <a class="btn btn-primary" style="cursor: pointer;" href='/webapps2025/pay';  >
      New
    </a>
  </div>


      <div class="container mt-4" style="overflow-y: auto;">

  {% if payments %}
    <div class="list-group" style="overflow-y: auto;">


      {% for payment in payments %}

        <div class="list-group-item d-flex justify-content-between align-items-center" style="overflow-y: auto;">

          <div>


            {% if payment.incoming %}
            <strong>From:</strong> {{ payment.sender.email }}<br>
            {% else %}
            <strong>To:</strong> {{ payment.receiver.email }}<br>
            {% endif %}

            <strong>Date:</strong> {{ payment.date|date:"Y-m-d H:i" }}
          </div>


            {% if payment.incoming %}
              <strong style="color: green;">+ {{ payment.receiver_amount }}</strong>
            {% else %}
              <strong style="color: red;">- {{ payment.sender_amount }}</strong>
            {% endif %}


        </div>

      {% endfor %}



    </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      No payments found.
    </div>
  {% endif %}







    </div>
  </div>
</div>
{% endblock %}

templates/payapp/requests.html
{% extends "signed_in.html" %}
{% block content %}

<div style="display: flex; height: calc(100vh - {{ nav_height }}); background-color: black;">
<div class="d-flex justify-content-center align-items-center flex-column flex-grow-1 ">


<div class="rounded shadow p-5 w-50" style="background-color: white; height: calc( calc(100vh - {{ nav_height }}) * 0.8 ); display: flex; flex-direction: column;">

  <div class="d-flex align-items-center justify-content-between">
    <h2>Requests</h2>

    <a class="btn btn-primary" style="cursor: pointer;" href='/webapps2025/request';  >
      New
    </a>
  </div>


  {% if messages %}
  <div class="mb-3">
      {% for message in messages %}
          <div class="alert alert-{% if 'error' in message.tags %}danger{% else %}{{ message.tags }}{% endif %} mb-2"
               role="alert">
              {{ message }}
          </div>
      {% endfor %}
  </div>
  {% endif %}


  <div class="container mt-4" style="overflow-y: auto;">


  {% if requests %}
  <div class="list-group" style="overflow-y: auto;">


      {% for request in requests %}
      <div class="list-group-item d-flex justify-content-between alight-items-center" style="overflow-y: auto;">

          <div class="d-flex align-items-center">
              <div class="d-flex flex-column">


                {% if request.incoming %}
                  <strong>You requested</strong>
                {% else %}
                  <strong>{{ request.sender.email }} requested</strong>
                {% endif %}

                <strong>Date: {{ request.date|date:"Y-m-d H:i" }}</strong><br>


                <strong>Status:  {{ request.status }}</strong>
              </div>


              {% if request.status == "Pending" and request.sender == user %}

              <form action="{% url 'approve' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="request_id" value="{{ request.id }}">

                <button class="btn btn-primary ms-5" style="cursor: pointer;" onclick="this.onsest('form').submit();">
                  ACCEPT
                </button>
              </form>

              <form action="{% url 'deny' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="request_id" value="{{ request.id }}">

                <button class="btn btn-danger ms-5" style="cursor: pointer;" onclick="this.onsest('form').submit();">
                  DENY
                </button>
              </form>


              {% endif %}

          </div>


          <div class="d-flex align-items-center">

            {% if request.status == "Approved" %}
              {% if request.incoming %}
                <strong style="color: green;">+ {{ request.receiver_amount }}</strong>
              {% else %}
                <strong style="color: red;">- {{ request.sender_amount }}</strong>
              {% endif %}
              
            {% else %}

              {% if request.incoming %}
                <strong >+ {{ request.receiver_amount }}</strong>
              {% else %}
                <strong >- {{ request.sender_amount }}</strong>
              {% endif %}


            {% endif %}

          </div>






      </div>
      {% endfor %}





  </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      No requests found.
    </div>
  {% endif %}





</div>


</div>


</div>
</div>
{% endblock %}