admin/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("login", views.signin, name="admin_login"),
    path("logout", views.sign_out, name="admin_logout"),
    path("register", views.admin_create, name="admin_create"),

    path("payments/<str:user_email>", views.view_payments, name="admin_payments"),
    path("requests/<str:user_email>", views.view_requests, name="admin_requests"),
]

register/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path("", views.register, name="register"),
]

webapps2025/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.shortcuts import HttpResponse
from django.http.response import HttpResponse

from accounts.views import home

urlpatterns = [
    path("webapps2025/admin/", include("admin.urls")),

    path("webapps2025/", include("accounts.urls")),

    path("webapps2025/register/", include("register.urls")),
    path('webapps2025/conversion/', include('conversion.urls')),
    path('webapps2025/', include('payapp.urls')),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


from decimal import Decimal


from utils.currency import precision, places


class Account(AbstractUser):
    CURRENCIES = [ 
        ("GBP", "GBP"),
        ("USD", "USD"), 
        ("EUR", "EUR")
    ]

    email = models.EmailField(unique=True, primary_key=True, null=False, blank=False)
    currency = models.CharField(max_length=3, choices=CURRENCIES, null=False, blank=False, default="GBP")
    username = models.CharField(max_length=50, blank=True, null=True, unique=True)
    balance = models.DecimalField(max_digits=precision, decimal_places=places, default=Decimal("750.00"), null=False, blank=False)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    @classmethod
    def get_default(cls, field_name: str):
        meta = getattr(cls, "_meta")
        return meta.get_field(field_name).default
    

register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from  accounts.models import Account

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    fullname = forms.CharField(max_length=255, label="Full Name")

    class Meta:
        model = Account
        fields = ['email', 'username', 'password1', 'password2', "currency", ]


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

        if not self.data.get('currency'):
            # sets the default 
            self.fields['currency'].initial = "GBP"

        self.fields['currency'].widget = forms.Select(choices=Account.CURRENCIES, attrs={'class':'currency-dropdown'})


    def clean_fullname(self):
        fullname = self.cleaned_data.get('fullname')
        name_parts = fullname.split(" ", 1)

        if len(name_parts) != 2:
            raise forms.ValidationError("Fullname must provide both first and last name")

        first, last = name_parts



        if len(first) < 1:
            raise forms.ValidationError("Fullname must provide first name")

        if len(last) < 1:
            raise forms.ValidationError("Fullname must provide last name")


        self.first = first
        self.last = last

        return fullname


    def save(self, commit=True):
        user = super().save(commit=False)

        user.first_name = self.first
        user.last_name = self.last

        user.save()
        return user

register/views.py
from django.http.response import HttpResponseServerError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login

from utils.currency import CurrencyAmount


from . forms import RegisterForm
from accounts.models import Account
from services.currency import call_conversion_api


from decimal import Decimal


from accounts.models import Account


from django.contrib import messages


def register_user_from_form(request, form: RegisterForm):
    default_currency = Account.get_default("currency")
    chosen_currency: str = form.cleaned_data["currency"]

    if (default_currency == chosen_currency):
        user = form.save()
        return user
    

    email = form.cleaned_data["email"]
    default_balance = Account.get_default("balance")



    result = call_conversion_api(request, default_currency, chosen_currency, str(default_balance))



    rate = CurrencyAmount(Decimal(result["rate"]))
    balance = CurrencyAmount(default_balance) * rate

    password = form.cleaned_data["password1"]


    user = Account(email=email, balance=balance.into(), currency=chosen_currency)
    user.set_password(password)
    user.save()
    

    print("came here")
    return user





def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            try:
                user = register_user_from_form(request, form)

            except Exception as e:
                return HttpResponseServerError("Internal server error, try again later")


            login(request, user)
            return redirect('home')


        exception = (list(form.errors.as_data().values())[0][0]).messages[0]
        messages.error(request, exception)
    else:
        form = RegisterForm()
    
    return render(request, 'register/register.html', {'form': form})


def index(request):
    return HttpResponse("hello, world. you are at index")

templates/register/register.html
{% extends "signed_out.html" %}



{% block content %}
<h2>Register</h2>
<form method="POST">
    {% csrf_token %}
    {# {{ form.as_p }} #}

    {% if messages %}
    <div class="mb-3">
        {% for message in messages %}
            <div class="alert alert-{% if 'error' in message.tags %}danger{% else %}{{ message.tags }}{% endif %} mb-2"
                 role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}


    <label for="email" >Email</label>
    <input type="email" name="email" id="id_email" class="form-control" required>

    <label for="password1" >Password</label>
    <input type="password" name="password1" id="id_password1" class="form-control" required>

    <label for="password2" >Confirm Password</label>
    <input type="password" name="password2" id="id_password2" class="form-control mb-2" required>


    <ul>
      <li>Your password can’t be too similar to your other personal information. </li>
        <li>Your password must contain at least 8 characters. </li>
        <li>Your password can’t be a commonly used password. </li>
        <li>Your password can’t be entirely numeric. </li>
    </ul>



    <label for="choice" >Currency</label>
    <select name="currency" id="id_currency" class="form-control">
        <option value="GBP">GBP</option>
        <option value="EUR">EUR</option>
        <option value="USD">USD</option>
    </select>


    <button type="submit">Register</button>
</form>
{% endblock %}